user_input1 = input("What is your favorite animal?\n")
print(">" + user_input1)
user_input2 = input("Why do you like them?\n")
print(">" + user_input2)
user_input3 = input("What sound do they make?\n")
print(">" + user_input3)
user_input4 = input("What color are they?\n")
print(">" + user_input4)
user_input5 = input("What do they eat?\n")
print(">" + user_input5)
user_input6 = input("Where do they live?\n")
print(">" + user_input6)
print("Your favorite animal is a " + user_input1 + " because " + user_input2 + "." + " They make a noise like " + user_input3 + " and they are " + user_input4 + "." + " They eat " + user_input5 + " and they live in " + user_input6 + ".")