user_input1 = input("What is your favorite animal?\n>")
user_input2 = input("Why do you like them?\n>")
user_input3 = input("What sound do they make?\n>")
user_input4 = input("What color are they?\n>")
user_input5 = input("What do they eat?\n>")
user_input6 = input("Where do they live?\n>")
print("Your favorite animal is a " + user_input1 + " because " + user_input2 + "." + " They make a noise like " + user_input3 + " and they are " + user_input4 + "." + " They eat " + user_input5 + " and they live in " + user_input6 + ".")