answer_1 = int(input("give me a whole number that is equal to 5\n>"))
print(answer_1==5)
answer_2= int(input("give me a whole number that is greater than 32\n>"))
print(answer_2>32)
answer_3 = int(input("give me a whole number that is less than 7\n>"))
print(answer_3<7)
answer_4 = int(input("give me a whole number that is greater than or equal to 8\n>"))
print(answer_4 >= 8)
answer_5 = int(input("give me a whole number that is less than or equal to 9\n>"))
print(answer_5 <= 9)